/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2021-12-02 05:14:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write(" <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Color Korea</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"./image/icon.ico\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/java.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/chart.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Fonts 고딕나눔 등록-->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- font-family: 'Nanum Gothic', sans-serif; 사용 -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Fonts 영어들-->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Mochiy+Pop+P+One&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <!--font-family: 'Mochiy Pop P One', sans-serif;-->\r\n");
      out.write("    \r\n");
      out.write("    <!-- GSAP & ScrollToPlugin -->\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/gsap/3.5.1/gsap.min.js\" integrity=\"sha512-IQLehpLoVS4fNzl7IfH8Iowfm5+RiMGtHykgZJl9AWMgqx0AmJ6cRWcB+GaGVtIsnC4voMfm8f2vwtY+6oPjpQ==\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/gsap/3.5.1/ScrollToPlugin.min.js\" integrity=\"sha512-nTHzMQK7lwWt8nL4KF6DhwLHluv6dVq/hNnj2PBN0xMl2KaMm1PM02csx57mmToPAodHmPsipoERRNn4pG7f+Q==\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"./js/jquery.min.js\"></script>\r\n");
      out.write("    <script defer src=\"./js/java.js\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"wrap\">\r\n");
      out.write("        <header>\r\n");
      out.write("            <div class=\"Head\">\r\n");
      out.write("                <a href=\"java.html\">\r\n");
      out.write("                    <h1>Color Korea</h1>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("\r\n");
      out.write("        <section class=\"content\">\r\n");
      out.write("            <section class=\"left_content\">\r\n");
      out.write("            <div class=\"sidecontent1\">\r\n");
      out.write("                <h1>Month Select</h1>\r\n");
      out.write("                <ul class=\"month_select\">\r\n");
      out.write("                    <li id=\"jan\">Jan</li>\r\n");
      out.write("                    <li id=\"feb\"><a href=\"#\">Feb</a></li>\r\n");
      out.write("                    <li id=\"mar\"><a href=\"#\">Mar</a></li>\r\n");
      out.write("                    <li id=\"apr\"><a href=\"#\">Apr</a></li>\r\n");
      out.write("                    <li id=\"may\"><a href=\"#\">May</a></li>\r\n");
      out.write("                    <li id=\"jun\"><a href=\"#\">Jun</a></li>\r\n");
      out.write("                    <li id=\"jul\"><a href=\"#\">Jul</a></li>\r\n");
      out.write("                    <li id=\"aug\"><a href=\"#\">Aug</a></li>\r\n");
      out.write("                    <li id=\"sep\"><a href=\"#\">Sep</a></li>\r\n");
      out.write("                    <li id=\"oct\"><a href=\"#\">Oct</a></li>\r\n");
      out.write("                    <li id=\"nov\"><a href=\"#\">Nov</a></li>\r\n");
      out.write("                    <li id=\"dec\"><a href=\"#\">Dec</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            </section>\r\n");
      out.write("            <div class=\"mainimage\">\r\n");
      out.write("                <!-- <img src=\"../image/제작자료1.png\" alt=\"\" usemap=\"#Map\"> -->\r\n");
      out.write("                <img src=\"../image/제작자료1.png\" alt=\"\">\r\n");
      out.write("                <!-- <map name=\"Map\" id=\"Map\">\r\n");
      out.write("                    <area shape=\"poly\" coords=\"146,41,99,88,110,127,137,111,153,135,139,146,110,143,118,205,170,204,205,177,206,132,184,119,183,94,191,83,164,61,141,36\" href=\"gyung.html\" alt=\"경기도\" id=\"gyeonggido\">\r\n");
      out.write("                </map> -->\r\n");
      out.write("                <div class=\"area\" id=\"seoul\">Seoul<br> <a href=\"seoul.html\" class=\"btn\">이동하기</a></div>\r\n");
      out.write("                <div id=\"seoul_1\"><img class=\"red\" id=\"seoul_red\" src=\"../image/red.png\" alt=\"\" style=\"width: 8px; height: 8px;\" ></div>\r\n");
      out.write("                <div class=\"area\" id=\"gyeonggi\">Gyeong<br>Gi <div><a href=\"gyung.html\" class=\"btn\">더보기</a></div></div>\r\n");
      out.write("                <div><img class=\"red\" id=\"gyeonggi_red\" src=\"../image/red.png\" alt=\"\" style=\"width: 8px; height: 8px;\" ></div>\r\n");
      out.write("                <div class=\"area\" id=\"chungbuk\">\r\n");
      out.write("                    <div> Chung<br>Buk <div><a href=\"chungbuk.html\" class=\"btn\">더보기</a></div></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div><img class=\"red\" id=\"chungbuk_red\" src=\"../image/red.png\" alt=\"\" style=\"width: 8px; height: 8px;\" ></div>\r\n");
      out.write("                <div class=\"area\" id=\"chungnam\">Chung<br>Nam <div><a href=\"chungnam.html\" class=\"btn\">더보기</a></div></div>\r\n");
      out.write("                <div><img class=\"red\" id=\"chungnam_red\" src=\"../image/red.png\" alt=\"\" style=\"width: 8px; height: 8px;\" ></div>\r\n");
      out.write("                <div class=\"area\" id=\"jeollanam\">Jeol<br>Nam <div><a href=\"jeolnam.html\" class=\"btn\">더보기</a></div></div>\r\n");
      out.write("                <div><img class=\"red\" id=\"jeollanam_red\" src=\"../image/red.png\" alt=\"\" style=\"width: 8px; height: 8px;\" ></div>\r\n");
      out.write("                <div class=\"area\" id=\"jeollabuk\">Jeol<br>Buk <div><a href=\"jeolbuk.html\" class=\"btn\">더보기</a></div></div>\r\n");
      out.write("                <div><img class=\"red\" id=\"jeollabuk_red\" src=\"../image/red.png\" alt=\"\" style=\"width: 8px; height: 8px;\" ></div>\r\n");
      out.write("                <div class=\"area\" id=\"gangwon\">Gang<br>Won <div><a href=\"gangwon.html\" class=\"btn\">더보기</a></div></div>\r\n");
      out.write("                <div><img class=\"red\" id=\"gangwon_red\" src=\"../image/red.png\" alt=\"\" style=\"width: 8px; height: 8px;\" ></div>\r\n");
      out.write("                <div class=\"area\" id=\"gyeongbuk\">Gyeong<br>Buk <div><a href=\"gyeongbuk.html\" class=\"btn\">더보기</a></div></div>\r\n");
      out.write("                <div><img class=\"red\" id=\"gyeongbuk_red\" src=\"../image/red.png\" alt=\"\" style=\"width: 8px; height: 8px;\" ></div>\r\n");
      out.write("                <div class=\"area\" id=\"gyeongnam\">Gyeong<br>Nam <div><a href=\"gyeongnam.html\" class=\"btn\">더보기</a></div></div>\r\n");
      out.write("                <div><img class=\"red\" id=\"gyeongnam_red\" src=\"../image/red.png\" alt=\"\" style=\"width: 8px; height: 8px;\" ></div>\r\n");
      out.write("                <svg width=\"100%\" height=\"100%\">\r\n");
      out.write("                    <line id=\"seoul_line\" stroke=\"black\"></line>\r\n");
      out.write("                    <line id=\"gyeonggi_line\" stroke=\"black\"></line>\r\n");
      out.write("                    <line id=\"chungbuk_line\" stroke=\"black\"></line>\r\n");
      out.write("                    <line id=\"chungnam_line\" stroke=\"black\"></line>\r\n");
      out.write("                    <line id=\"jeollabuk_line\" stroke=\"black\"></line>\r\n");
      out.write("                    <line id=\"jeollanam_line\" stroke=\"black\"></line>\r\n");
      out.write("                    <line id=\"gangwon_line\" stroke=\"black\"></line>\r\n");
      out.write("                    <line id=\"gyeongbuk_line\" stroke=\"black\"></line>\r\n");
      out.write("                    <line id=\"gyeongnam_line\" stroke=\"black\"></line>\r\n");
      out.write("                </svg>\r\n");
      out.write("            </div>\r\n");
      out.write("            <section class=\"right_content\">\r\n");
      out.write("            <div class=\"sidecontent2\">\r\n");
      out.write("                <h1>외국인 방문수</h1>\r\n");
      out.write("                <div class=\"charts\">\r\n");
      out.write("                    <span>Japan</span>\r\n");
      out.write("                    <div id=\"japen\" class=\"charts__chart chart--p32 chart--grey\" data-percent></div><!-- /.charts__chart -->\r\n");
      out.write("                    <span>USA</span>\r\n");
      out.write("                    <div id=\"usa\" class=\"charts__chart chart--p60 chart--grey\" data-percent></div><!-- /.charts__chart -->\r\n");
      out.write("                    <span>China</span>\r\n");
      out.write("                    <div id=\"china\" class=\"charts__chart chart--p40 chart--grey\" data-percent></div><!-- /.charts__chart -->\r\n");
      out.write("                    <span>Korean(교포)</span>\r\n");
      out.write("                    <div id=\"kor\" class=\"charts__chart chart--p20 chart--grey\" data-percent></div><!-- /.charts__chart -->\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("           \r\n");
      out.write("            </section>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <footer>\r\n");
      out.write("\r\n");
      out.write("        </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
