/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2021-12-15 07:46:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import restaurant.RDAO;
import restaurant.RDTO;
import java.util.List;

public final class gyeonggi1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1639027132258L));
    _jspx_dependants.put("jar:file:/C:/Users/user/Desktop/project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ColorKorea/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("restaurant.RDAO");
    _jspx_imports_classes.add("restaurant.RDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");

RDAO rDAO = new RDAO();
RDTO dto = new RDTO();
dto.setArea("경기");
List<RDTO> Rest = rDAO.selectRestaurant(dto);


      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Color Korea</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"../image/icon.ico\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/localpage.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/chart.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Fonts 고딕나눔 등록-->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- font-family: 'Nanum Gothic', sans-serif; 사용 -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Fonts 영어들-->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Mochiy+Pop+P+One&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- GSAP & ScrollToPlugin -->\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/gsap/3.5.1/gsap.min.js\"\r\n");
      out.write("        integrity=\"sha512-IQLehpLoVS4fNzl7IfH8Iowfm5+RiMGtHykgZJl9AWMgqx0AmJ6cRWcB+GaGVtIsnC4voMfm8f2vwtY+6oPjpQ==\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/gsap/3.5.1/ScrollToPlugin.min.js\"\r\n");
      out.write("        integrity=\"sha512-nTHzMQK7lwWt8nL4KF6DhwLHluv6dVq/hNnj2PBN0xMl2KaMm1PM02csx57mmToPAodHmPsipoERRNn4pG7f+Q==\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- ScrollMagic 사용-->\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.8/ScrollMagic.min.js\"\r\n");
      out.write("        integrity=\"sha512-8E3KZoPoZCD+1dgfqhPbejQBnQfBXe8FuwL4z/c8sTrgeDMFEnoyTlH3obB4/fV+6Sg0a0XF+L/6xS4Xx1fUEg==\"\r\n");
      out.write("        crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Material Icon 사용-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\r\n");
      out.write("\r\n");
      out.write("    <!-- lodash 사용   -->\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.20/lodash.min.js\"\r\n");
      out.write("        integrity=\"sha512-90vH1Z83AJY9DmlWa8WkjkV79yfS2n2Oxhsi2dZbIv0nC4E6m5AbH8Nh156kkM7JePmqD6tcZsfad1ueoaovww==\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"../js/jquery.min.js\"></script>\r\n");
      out.write("    <!-- <script defer src=\"../js/main.js\"></script> -->\r\n");
      out.write("    <script defer src=\"../js/localpage.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-latest.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"wrap\">\r\n");
      out.write("        <header>\r\n");
      out.write("            <div class=\"Head\">\r\n");
      out.write("                <a href=\"java.html\">\r\n");
      out.write("                    <h1>Color Korea</h1>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <nav>\r\n");
      out.write("                <ul class=\"Menu\">\r\n");
      out.write("                    <li id=\"bt01\" onclick=\"fnMove('1')\"><a href=\"#\">Food</a></li>\r\n");
      out.write("                    <li id=\"bt02\" onclick=\"fnMove('2')\"><a href=\"#\">Activity</a></li>\r\n");
      out.write("                    <li id=\"bt03\" onclick=\"fnMove('3')\"><a href=\"#\">Healing</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </header>\r\n");
      out.write("\r\n");
      out.write("        <div>\r\n");
      out.write("            <ul class=\"SideMenu\">\r\n");
      out.write("                <li id=\"bt01\" onclick=\"fnMove('1')\"><a href=\"#\"><img class=\"food_icon\" src=\"../image/food_icon.png\" width=\"40px\"><br>Food</a></li>\r\n");
      out.write("                <li id=\"bt02\" onclick=\"fnMove('2')\"><a href=\"#\"><img class=\"activity_icon\" src=\"../image/activity_icon.jpg\" width=\"60px\"><br>Activity</a></li>\r\n");
      out.write("                <li id=\"bt03\" onclick=\"fnMove('3')\"><a href=\"#\"><img class=\"Healing_icon\" src=\"../image/healing_icon.png\" width=\"60px\"><br>Healing</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"innerwrap\">\r\n");
      out.write("            <div class=\"sub1\">\r\n");
      out.write("                <div class=\"about_area\">\r\n");
      out.write("                    <h2>GyeongGi Food <b>TOP 6</b></h2>\r\n");
      out.write("                    <div class=\"about_box\">\r\n");
      out.write("                        <ul class=\"place_list box_inner clear\">\r\n");
      out.write("                            <li><a href=\"#\"\r\n");
      out.write("                                    onclick=\"$('.popup_base');$('.food1_pop').show();\">\r\n");
      out.write("                                    <img class=\"img_topplace\" src=\"../image/gyungki1.png\" alt=\"다리를 높이 들어 운동\" />\r\n");
      out.write("                                    <h3>");
      out.print(Rest.get(0).getName());
      out.write("</h3>\r\n");
      out.write("                                    <p class=\"txt\">");
      out.print(Rest.get(0).getContent());
      out.write("</p>\r\n");
      out.write("                                    <span class=\"view\">VIEW</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><a href=\"#\"\r\n");
      out.write("                                    onclick=\"$('.popup_base').css('height',$(document).height());$('.food2_pop').show();\">\r\n");
      out.write("                                    <img class=\"img_topplace\" src=\"../image/gyungki1.png\" alt=\"바닷가에서 스트레칭\" />\r\n");
      out.write("                                    <h3>");
      out.print(Rest.get(1).getName());
      out.write("</h3>\r\n");
      out.write("                                    <p class=\"txt\">");
      out.print(Rest.get(1).getContent());
      out.write("</p>\r\n");
      out.write("                                    <span class=\"view\">VIEW</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><a href=\"#\"\r\n");
      out.write("                                    onclick=\"$('.popup_base').css('height',$(document).height());$('..food3_pop').show();\">\r\n");
      out.write("                                    <img class=\"img_topplace\" src=\"../image/gyungki1.png\" alt=\"앉아서 스트레칭\" />\r\n");
      out.write("                                    <h3>");
      out.print(Rest.get(2).getName());
      out.write("</h3>\r\n");
      out.write("                                    <p class=\"txt\">");
      out.print(Rest.get(2).getContent());
      out.write("</p>\r\n");
      out.write("                                    <span class=\"view\">VIEW</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><a href=\"#\"\r\n");
      out.write("                                    onclick=\"$('.popup_base').css('height',$(document).height());$('.food4_pop').show();\">\r\n");
      out.write("                                    <img class=\"img_topplace\" src=\"../image/gyungki1.png\" alt=\"앉아서 스트레칭\" />\r\n");
      out.write("                                    <h3>");
      out.print(Rest.get(3).getName());
      out.write("</h3>\r\n");
      out.write("                                    <p class=\"txt\">");
      out.print(Rest.get(3).getContent());
      out.write("</p>\r\n");
      out.write("                                    <span class=\"view\">VIEW</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><a href=\"#\"\r\n");
      out.write("                                    onclick=\"$('.popup_base').css('height',$(document).height());$('.food5_pop').show();\">\r\n");
      out.write("                                    <img class=\"img_topplace\" src=\"../image/gyungki1.png\" alt=\"앉아서 스트레칭\" />\r\n");
      out.write("                                    <h3>");
      out.print(Rest.get(4).getName());
      out.write("</h3>\r\n");
      out.write("                                    <p class=\"txt\">");
      out.print(Rest.get(4).getContent());
      out.write("</p>\r\n");
      out.write("                                    <span class=\"view\">VIEW</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li><a href=\"#\"\r\n");
      out.write("                                    onclick=\"$('.popup_base').css('height',$(document).height());$('.food6_pop').show();\">\r\n");
      out.write("                                    <img class=\"img_topplace\" src=\"../image/gyungki1.png\" alt=\"앉아서 스트레칭\" />\r\n");
      out.write("                                    <h3>");
      out.print(Rest.get(5).getName());
      out.write("</h3>\r\n");
      out.write("                                    <p class=\"txt\">");
      out.print(Rest.get(5).getContent());
      out.write("</p>\r\n");
      out.write("                                    <span class=\"view\">VIEW</span>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"sub2\">\r\n");
      out.write("                <section class=\"gallary_section2\">\r\n");
      out.write("                    <h2>GyeongGi Activity <b>TOP 3</b></h2>\r\n");
      out.write("                    <ul class=\"program_list clear\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <img class=\"img_place\" src=\"../image/gyungki1.png\"/>\r\n");
      out.write("                            <h3>이응노 미술관</h3>\r\n");
      out.write("                            <p class=\"subttl\">2019.01 ~ 2019.03</p>\r\n");
      out.write("                            <div class=\"program_content\">\r\n");
      out.write("                                <p>고암 이응노 화백의 예술세계와 작품들을 감상할 수 있다. <span class=\"subtxt\">대전에 위치한 이응노 미술관에서는 대전과 파리, 한국과 프랑스, 아시아와 유럽의 커뮤니케이션이 일어난다.</span></p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p class=\"btn_more\"><a href=\"javascript:;\">More</a></p>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <img class=\"img_place\" src=\"../image/gyungki1.png\"/>\r\n");
      out.write("                            <h3>김유정문학촌</h3>\r\n");
      out.write("                            <p class=\"subttl\">2019.01 ~ 2019.03</p>\r\n");
      out.write("                            <div class=\"program_content\">\r\n");
      out.write("                                <p>강원도 춘천시에서는 김유정이 우리나라 제일의 소설가인 것처럼 정성을 다해 김유정 문학촌을 꾸몄다. <span class=\"subtxt\">기념관은 물론이고 소설의 마지막 장면을 실제크기 동상으로 재연하기도 했다. 우리를 감동시킨 많은 다른 문학가, 예술인들도 해당 지자체에서 성의를 다해 기렸으면 하는 바램이다.</span></p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p class=\"btn_more\"><a href=\"javascript:;\">More</a></p>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <img class=\"img_place\" src=\"../image/gyungki1.png\"/>\r\n");
      out.write("                            <h3>책과 인쇄 박물관</h3>\r\n");
      out.write("                            <p class=\"subttl\">2019.01 ~ 2019.03</p>\r\n");
      out.write("                            <div class=\"program_content\">\r\n");
      out.write("                                <p>생각보다 작은 공간이지만 활자가 문명에 끼친 어마어마한 영향력이 초판본들에서 느껴진다. <span class=\"subtxt\">박물만 볼 수 있는 것이 아니라 아직까지도 그 시절에 인쇄 과정을 손수 체험 할 수 있는 시간을 제공하고 있다.</span></p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p class=\"btn_more\"><a href=\"javascript:;\">More</a></p>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        \r\n");
      out.write("                    </ul>\r\n");
      out.write("                </section>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"sub3\">\r\n");
      out.write("                <section class=\"gallary_section2\">\r\n");
      out.write("                    <h2>GyeongGi Healing <b>TOP 3</b></h2>\r\n");
      out.write("                    <ul class=\"program_list clear\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <img class=\"img_place\" src=\"../image/gyungki1.png\"/>\r\n");
      out.write("                            <h3>이응노 미술관</h3>\r\n");
      out.write("                            <p class=\"subttl\">2019.01 ~ 2019.03</p>\r\n");
      out.write("                            <div class=\"program_content\">\r\n");
      out.write("                                <p>고암 이응노 화백의 예술세계와 작품들을 감상할 수 있다. <span class=\"subtxt\">대전에 위치한 이응노 미술관에서는 대전과 파리, 한국과 프랑스, 아시아와 유럽의 커뮤니케이션이 일어난다.</span></p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p class=\"btn_more\"><a href=\"javascript:;\">More</a></p>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <img class=\"img_place\" src=\"../image/gyungki1.png\"/>\r\n");
      out.write("                            <h3>김유정문학촌</h3>\r\n");
      out.write("                            <p class=\"subttl\">2019.01 ~ 2019.03</p>\r\n");
      out.write("                            <div class=\"program_content\">\r\n");
      out.write("                                <p>강원도 춘천시에서는 김유정이 우리나라 제일의 소설가인 것처럼 정성을 다해 김유정 문학촌을 꾸몄다. <span class=\"subtxt\">기념관은 물론이고 소설의 마지막 장면을 실제크기 동상으로 재연하기도 했다. 우리를 감동시킨 많은 다른 문학가, 예술인들도 해당 지자체에서 성의를 다해 기렸으면 하는 바램이다.</span></p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p class=\"btn_more\"><a href=\"javascript:;\">More</a></p>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <img class=\"img_place\" src=\"../image/gyungki1.png\"/>\r\n");
      out.write("                            <h3>책과 인쇄 박물관</h3>\r\n");
      out.write("                            <p class=\"subttl\">2019.01 ~ 2019.03</p>\r\n");
      out.write("                            <div class=\"program_content\">\r\n");
      out.write("                                <p>생각보다 작은 공간이지만 활자가 문명에 끼친 어마어마한 영향력이 초판본들에서 느껴진다. <span class=\"subtxt\">박물만 볼 수 있는 것이 아니라 아직까지도 그 시절에 인쇄 과정을 손수 체험 할 수 있는 시간을 제공하고 있다.</span></p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p class=\"btn_more\"><a href=\"javascript:;\">More</a></p>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        \r\n");
      out.write("                    </ul>\r\n");
      out.write("                </section>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <footer>\r\n");
      out.write("\r\n");
      out.write("        </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"to-top\">\r\n");
      out.write("        <div class=\"material-icons\">arrow_upward</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- contact_pop -->\r\n");
      out.write("    <div class=\"popup_base food1_pop\">\r\n");
      out.write("        <div class=\"pop_content\">\r\n");
      out.write("            <p class=\"btn_xpop\"><a href=\"#\" onclick=\"$(this).parent().parent().parent().hide();\">닫기</a></p>\r\n");
      out.write("            <ul class=\"pop_list\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <h2 class=\"tit_pop\">Gwangneung Hanok House.</h2>\r\n");
      out.write("                    <img class=\"pop_img\" src=\"../image/gyungki1.png\"/>\r\n");
      out.write("                    <div class=\"pop_txt\">\r\n");
      out.write("                        <div class=\"Info1\">\r\n");
      out.write("                            <p>Address<br>&nbsp;</p>\r\n");
      out.write("                            <p>Phone number</p>\r\n");
      out.write("                            <p>Opening Time</p>\r\n");
      out.write("                            <p>&nbsp;</p>\r\n");
      out.write("                            <p>Menu</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"Info2\">\r\n");
      out.write("                            <p>36 Gwangneungnae-ro, Jinjeop-eup, Namyangju-si, Gyeonggi-do.</p>\r\n");
      out.write("                            <p>031-574-6630</p>\r\n");
      out.write("                            <p>11:00-15:50</p>\r\n");
      out.write("                            <p>11:00-20:50</p>\r\n");
      out.write("                            <p>Charcoal Grilled Pork (200g) <span>14,000 won</span></p>\r\n");
      out.write("                            <p>Charcoal Grilled Beef (200g) <span>24,000 won</span></p>\r\n");
      out.write("                            <p>Bibim Makguksu <span>10,000 won</span></p>\r\n");
      out.write("                            <p>Buckwheat noodles <span>10,000 won</span></p>\r\n");
      out.write("                            <p>Pyongyang Cold Noodles <span>12,000 won</span></p>\r\n");
      out.write("                        </div>              \r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- //contact_pop -->\r\n");
      out.write("\r\n");
      out.write("    <!-- space_pop -->\r\n");
      out.write("    <div class=\"popup_base food2_pop\">\r\n");
      out.write("        <div class=\"pop_content\">\r\n");
      out.write("            <p class=\"btn_xpop\"><a href=\"#\" onclick=\"$(this).parent().parent().parent().hide();\">닫기</a></p>\r\n");
      out.write("            <ul class=\"pop_list\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <h2 class=\"tit_pop\">원주 뮤지엄 '산'</h2>\r\n");
      out.write("                    <img class=\"pop_img\" src=\"img/img_pop2_1.jpg\"/>\r\n");
      out.write("                    <div class=\"pop_txt\">\r\n");
      out.write("                        <div class=\"Info1\">\r\n");
      out.write("                            <p>Address<br>&nbsp;</p>\r\n");
      out.write("                            <p>Phone number</p>\r\n");
      out.write("                            <p>Opening Time</p>\r\n");
      out.write("                            <p>&nbsp;</p>\r\n");
      out.write("                            <p>Menu</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"Info2\">\r\n");
      out.write("                            <p>36 Gwangneungnae-ro, Jinjeop-eup, Namyangju-si, Gyeonggi-do.</p>\r\n");
      out.write("                            <p>031-574-6630</p>\r\n");
      out.write("                            <p>11:00-15:50</p>\r\n");
      out.write("                            <p>11:00-20:50</p>\r\n");
      out.write("                            <p>Charcoal Grilled Pork (200g) <span>14,000 won</span></p>\r\n");
      out.write("                            <p>Charcoal Grilled Beef (200g) <span>24,000 won</span></p>\r\n");
      out.write("                            <p>Bibim Makguksu <span>10,000 won</span></p>\r\n");
      out.write("                            <p>Buckwheat noodles <span>10,000 won</span></p>\r\n");
      out.write("                            <p>Pyongyang Cold Noodles <span>12,000 won</span></p>\r\n");
      out.write("                        </div>              \r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- //space_pop -->\r\n");
      out.write("\r\n");
      out.write("    <!-- program_pop -->\r\n");
      out.write("    <div class=\"popup_base food3_pop\">\r\n");
      out.write("        <div class=\"pop_content\">\r\n");
      out.write("            <p class=\"btn_xpop\"><a href=\"#\" onclick=\"$(this).parent().parent().parent().hide();\">닫기</a></p>\r\n");
      out.write("            <ul class=\"pop_list\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <h2 class=\"tit_pop\">일본 만국박람회 기념 공원</h2>\r\n");
      out.write("                    <img class=\"pop_img\" src=\"img/img_pop3_1.jpg\"/>\r\n");
      out.write("                    <div class=\"pop_txt\">\r\n");
      out.write("                        <div class=\"Info1\">\r\n");
      out.write("                            <p>Address<br>&nbsp;</p>\r\n");
      out.write("                            <p>Phone number</p>\r\n");
      out.write("                            <p>Opening Time</p>\r\n");
      out.write("                            <p>&nbsp;</p>\r\n");
      out.write("                            <p>Menu</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"Info2\">\r\n");
      out.write("                            <p>36 Gwangneungnae-ro, Jinjeop-eup, Namyangju-si, Gyeonggi-do.</p>\r\n");
      out.write("                            <p>031-574-6630</p>\r\n");
      out.write("                            <p>11:00-15:50</p>\r\n");
      out.write("                            <p>11:00-20:50</p>\r\n");
      out.write("                            <p>Charcoal Grilled Pork (200g) <span>14,000 won</span></p>\r\n");
      out.write("                            <p>Charcoal Grilled Beef (200g) <span>24,000 won</span></p>\r\n");
      out.write("                            <p>Bibim Makguksu <span>10,000 won</span></p>\r\n");
      out.write("                            <p>Buckwheat noodles <span>10,000 won</span></p>\r\n");
      out.write("                            <p>Pyongyang Cold Noodles <span>12,000 won</span></p>\r\n");
      out.write("                        </div>              \r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"popup_base food4_pop\">\r\n");
      out.write("        <div class=\"pop_content\">\r\n");
      out.write("            <p class=\"btn_xpop\"><a href=\"#\" onclick=\"$(this).parent().parent().parent().hide();\">닫기</a></p>\r\n");
      out.write("            <ul class=\"pop_list\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <h2 class=\"tit_pop\">일본 만국박람회 기념 공원</h2>\r\n");
      out.write("                    <img class=\"pop_img\" src=\"img/img_pop3_1.jpg\"/>\r\n");
      out.write("                    <div class=\"pop_txt\">\r\n");
      out.write("                        <div class=\"Info1\">\r\n");
      out.write("                            <p>Address<br>&nbsp;</p>\r\n");
      out.write("                            <p>Phone number</p>\r\n");
      out.write("                            <p>Opening Time</p>\r\n");
      out.write("                            <p>&nbsp;</p>\r\n");
      out.write("                            <p>Menu</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"Info2\">\r\n");
      out.write("                            <p>36 Gwangneungnae-ro, Jinjeop-eup, Namyangju-si, Gyeonggi-do.</p>\r\n");
      out.write("                            <p>031-574-6630</p>\r\n");
      out.write("                            <p>11:00-15:50</p>\r\n");
      out.write("                            <p>11:00-20:50</p>\r\n");
      out.write("                            <p>Charcoal Grilled Pork (200g) <span>14,000 won</span></p>\r\n");
      out.write("                            <p>Charcoal Grilled Beef (200g) <span>24,000 won</span></p>\r\n");
      out.write("                            <p>Bibim Makguksu <span>10,000 won</span></p>\r\n");
      out.write("                            <p>Buckwheat noodles <span>10,000 won</span></p>\r\n");
      out.write("                            <p>Pyongyang Cold Noodles <span>12,000 won</span></p>\r\n");
      out.write("                        </div>              \r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"popup_base food5_pop\">\r\n");
      out.write("        <div class=\"pop_content\">\r\n");
      out.write("            <p class=\"btn_xpop\"><a href=\"#\" onclick=\"$(this).parent().parent().parent().hide();\">닫기</a></p>\r\n");
      out.write("            <ul class=\"pop_list\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <h2 class=\"tit_pop\">일본 만국박람회 기념 공원</h2>\r\n");
      out.write("                    <img class=\"pop_img\" src=\"img/img_pop3_1.jpg\"/>\r\n");
      out.write("                    <div class=\"pop_txt\">\r\n");
      out.write("                        <div class=\"Info1\">\r\n");
      out.write("                            <p>Address<br>&nbsp;</p>\r\n");
      out.write("                            <p>Phone number</p>\r\n");
      out.write("                            <p>Opening Time</p>\r\n");
      out.write("                            <p>&nbsp;</p>\r\n");
      out.write("                            <p>Menu</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"Info2\">\r\n");
      out.write("                            <p>36 Gwangneungnae-ro, Jinjeop-eup, Namyangju-si, Gyeonggi-do.</p>\r\n");
      out.write("                            <p>031-574-6630</p>\r\n");
      out.write("                            <p>11:00-15:50</p>\r\n");
      out.write("                            <p>11:00-20:50</p>\r\n");
      out.write("                            <p>Charcoal Grilled Pork (200g) <span>14,000 won</span></p>\r\n");
      out.write("                            <p>Charcoal Grilled Beef (200g) <span>24,000 won</span></p>\r\n");
      out.write("                            <p>Bibim Makguksu <span>10,000 won</span></p>\r\n");
      out.write("                            <p>Buckwheat noodles <span>10,000 won</span></p>\r\n");
      out.write("                            <p>Pyongyang Cold Noodles <span>12,000 won</span></p>\r\n");
      out.write("                        </div>              \r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"popup_base food6_pop\">\r\n");
      out.write("        <div class=\"pop_content\">\r\n");
      out.write("            <p class=\"btn_xpop\"><a href=\"#\" onclick=\"$(this).parent().parent().parent().hide();\">닫기</a></p>\r\n");
      out.write("            <ul class=\"pop_list\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <h2 class=\"tit_pop\">일본 만국박람회 기념 공원</h2>\r\n");
      out.write("                    <img class=\"pop_img\" src=\"img/img_pop3_1.jpg\"/>\r\n");
      out.write("                    <div class=\"pop_txt\">\r\n");
      out.write("                        <div class=\"Info1\">\r\n");
      out.write("                            <p>Address<br>&nbsp;</p>\r\n");
      out.write("                            <p>Phone number</p>\r\n");
      out.write("                            <p>Opening Time</p>\r\n");
      out.write("                            <p>&nbsp;</p>\r\n");
      out.write("                            <p>Menu</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"Info2\">\r\n");
      out.write("                            <p>36 Gwangneungnae-ro, Jinjeop-eup, Namyangju-si, Gyeonggi-do.</p>\r\n");
      out.write("                            <p>031-574-6630</p>\r\n");
      out.write("                            <p>11:00-15:50</p>\r\n");
      out.write("                            <p>11:00-20:50</p>\r\n");
      out.write("                            <p>Charcoal Grilled Pork (200g) <span>14,000 won</span></p>\r\n");
      out.write("                            <p>Charcoal Grilled Beef (200g) <span>24,000 won</span></p>\r\n");
      out.write("                            <p>Bibim Makguksu <span>10,000 won</span></p>\r\n");
      out.write("                            <p>Buckwheat noodles <span>10,000 won</span></p>\r\n");
      out.write("                            <p>Pyongyang Cold Noodles <span>12,000 won</span></p>\r\n");
      out.write("                        </div>              \r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
