/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2021-12-09 00:44:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import restaurant.RDAO;
import restaurant.RDTO;
import java.util.List;

public final class gyungki_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("restaurant.RDAO");
    _jspx_imports_classes.add("restaurant.RDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

RDAO rDAO = new RDAO();
RDTO dto = new RDTO();

List<RDTO> Rest = rDAO.selectRestaurant(dto);


      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Color Korea</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"../image/icon.ico\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/gyung.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/chart.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Fonts 고딕나눔 등록-->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- font-family: 'Nanum Gothic', sans-serif; 사용 -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Fonts 영어들-->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Mochiy+Pop+P+One&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- GSAP & ScrollToPlugin -->\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/gsap/3.5.1/gsap.min.js\"\r\n");
      out.write("        integrity=\"sha512-IQLehpLoVS4fNzl7IfH8Iowfm5+RiMGtHykgZJl9AWMgqx0AmJ6cRWcB+GaGVtIsnC4voMfm8f2vwtY+6oPjpQ==\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/gsap/3.5.1/ScrollToPlugin.min.js\"\r\n");
      out.write("        integrity=\"sha512-nTHzMQK7lwWt8nL4KF6DhwLHluv6dVq/hNnj2PBN0xMl2KaMm1PM02csx57mmToPAodHmPsipoERRNn4pG7f+Q==\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- ScrollMagic 사용-->\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.8/ScrollMagic.min.js\"\r\n");
      out.write("        integrity=\"sha512-8E3KZoPoZCD+1dgfqhPbejQBnQfBXe8FuwL4z/c8sTrgeDMFEnoyTlH3obB4/fV+6Sg0a0XF+L/6xS4Xx1fUEg==\"\r\n");
      out.write("        crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Material Icon 사용-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\r\n");
      out.write("\r\n");
      out.write("    <!-- lodash 사용   -->\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.20/lodash.min.js\"\r\n");
      out.write("        integrity=\"sha512-90vH1Z83AJY9DmlWa8WkjkV79yfS2n2Oxhsi2dZbIv0nC4E6m5AbH8Nh156kkM7JePmqD6tcZsfad1ueoaovww==\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"../js/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"../js/main.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-latest.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"wrap\">\r\n");
      out.write("        <header>\r\n");
      out.write("            <div class=\"Head\">\r\n");
      out.write("                <a href=\"java.html\">\r\n");
      out.write("                    <h1>Color Korea</h1>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <nav>\r\n");
      out.write("                <ul class=\"Menu\">\r\n");
      out.write("                    <li id=\"bt01\" onclick=\"fnMove('1')\"><a href=\"#\">Food</a></li>\r\n");
      out.write("                    <li id=\"bt02\" onclick=\"fnMove('2')\"><a href=\"#\">adventure</a></li>\r\n");
      out.write("                    <li id=\"bt03\" onclick=\"fnMove('3')\"><a href=\"#\">Nature</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </header>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"innerwrap\">\r\n");
      out.write("            <div class=\"sub1\">\r\n");
      out.write("                <section class=\"gallary_section1\">\r\n");
      out.write("                    <ul class=\"gallary_list\">\r\n");
      out.write("                        <li><a href=\"\"><img src=\"../image/gyungki1.png\" alt=\"\"></a></li>\r\n");
      out.write("                        <li><a href=\"\"><img src=\"../image/gyungki1.png\" alt=\"\"></a></li>\r\n");
      out.write("                        <li><a href=\"\"><img src=\"../image/gyungki1.png\" alt=\"\"></a></li>\r\n");
      out.write("                        <li><a href=\"\"><img src=\"../image/gyungki1.png\" alt=\"\"></a></li>\r\n");
      out.write("                        <li><a href=\"\"><img src=\"../image/gyungki1.png\" alt=\"\"></a></li>\r\n");
      out.write("                        <li><a href=\"\"><img src=\"../image/gyungki1.png\" alt=\"\"></a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </section>\r\n");
      out.write("                <section class=\"content\">\r\n");
      out.write("                    <div class=\"mainimage\">\r\n");
      out.write("                        <img src=\"../image/제작자료3.png\" alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </section>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"sub2\">\r\n");
      out.write("                <section class=\"gallary_section2\">\r\n");
      out.write("                    <ul class=\"gallary_list\">\r\n");
      out.write("                        <li><a href=\"\"><img src=\"../image/gyungki1.png\" alt=\"\"></a></li>\r\n");
      out.write("                        <li><a href=\"\"><img src=\"../image/gyungki1.png\" alt=\"\"></a></li>\r\n");
      out.write("                        <li><a href=\"\"><img src=\"../image/gyungki1.png\" alt=\"\"></a></li>\r\n");
      out.write("                        <li><a href=\"\"><img src=\"../image/gyungki1.png\" alt=\"\"></a></li>\r\n");
      out.write("                        <li><a href=\"\"><img src=\"../image/gyungki1.png\" alt=\"\"></a></li>\r\n");
      out.write("                        <li><a href=\"\"><img src=\"../image/gyungki1.png\" alt=\"\"></a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </section>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"sub3\">\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"sub4\">\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <footer>\r\n");
      out.write("\r\n");
      out.write("        </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"to-top\">\r\n");
      out.write("        <div class=\"material-icons\">arrow_upward</div>\r\n");
      out.write("    </div>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
